// ---------------------------------------------------------------
// 汉化版添加的ruby式注释
// ---------------------------------------------------------------
//名词解释部分
#define @ruby死后世界战线 ruby("死后世界战线") "SSS" ruby
#define @ruby没有活着的感觉 ruby("含义为“活得提心吊胆”") "没有活着的感觉" ruby
#define @ruby婚前忧郁症 ruby("Marriage Blues") "婚前忧郁症" ruby
#define @ruby性取向 ruby("取向") "想法" ruby
#define @ruby龙卷风行动_带省略号 ruby("龙卷风行动") "OPERATION…TORNADO" ruby

//引用外部注释部分
#define @ruby注释1_格雷西家族 ruby("详情见注释1") "格雷西家族" ruby
#define @ruby注释2_ARENA ruby("详情见注释2") "ARENA" ruby

//餐品注释部分
#define	@ruby餐品1_炸猪排套餐 ruby("详情见餐品注释1") "炸猪排套餐" ruby
#define	@ruby餐品2_冬阴功咖喱 ruby("详情见餐品注释2") "冬阴功咖喱" ruby
#define	@ruby餐品10_方盒鳗鱼饭 ruby("详情见餐品注释3") "鳗鱼" ruby
#define	@ruby餐品3_味噌猪排盖饭 ruby("详情见餐品注释4") "味噌猪排盖饭" ruby
#define	@ruby餐品4_焗饭 ruby("详情见餐品注释5") "芝士焗饭" ruby
#define	@ruby餐品5_法式长条泡芙 ruby("详情见餐品注释6") "法式巧克力长条泡芙" ruby
#define	@ruby餐品6_盐味拉面 ruby("详情见餐品注释7") "盐味拉面" ruby
#define	@ruby餐品7_酱油拉面 ruby("详情见餐品注释8") "酱油拉面" ruby
#define	@ruby餐品8_南蛮炸鸡套餐 ruby("详情见餐品注释9") "南蛮炸鸡套餐" ruby
#define	@ruby餐品9_卷面 ruby("详情见餐品注释10") "卷面" ruby
#define	@ruby餐品11_玛格丽特披萨 ruby("详情见餐品注释11") "玛格丽特披萨" ruby
#define	@ruby餐品12_火腿热狗 ruby("详情见餐品注释12") "火腿热狗" ruby
#define	@ruby餐品13_炸牡蛎套餐 ruby("详情见餐品注释13") "炸牡蛎套餐" ruby
#define	@ruby餐品14_台湾臭豆腐 ruby("详情见餐品注释14") "台湾特产" ruby

//歌曲注释部分
#define	@ruby歌曲1_HURRYUP ruby("详情见歌曲注释1") "Hurry up!" ruby
#define	@ruby歌曲2_太陽のKomachiAngel ruby("详情见歌曲注释2") "认真来场" ruby