/********************************************************
*														*
*						ルビ							*
*														*
*********************************************************/
// ruby("ぶんしょう") 文章 ruby
//#define		@ruby立直		ruby("リーチ") 立直 ruby
#define			@rubyＳＳＳ		ruby("スリーエス") ＳＳＳ ruby
#define			@ruby剣			ruby("つるぎ") 剣 ruby
#define			@ruby気			ruby("け") 気 ruby
#define			@ruby大事		ruby("おおごと") 大事 ruby
#define			@ruby自由		ruby("うた") 自由 ruby
#define			@ruby赤心慶福	ruby("せきしんけいふく") 赤心慶福 ruby
#define			@ruby結弦		ruby("ゆずる") 結弦 ruby
#define			@ruby鈴			ruby("りん") 鈴 ruby
#define			@ruby花紗鈴		ruby("きゃさりん") 花紗鈴 ruby
#define			@ruby同			ruby("おんな") 同 ruby
#define			@ruby金盞花		ruby("きんせんか") 金盞花 ruby
#define			@ruby犇			ruby("ひし") 犇 ruby
#define			@ruby攪乱		ruby("かくらん") 攪乱 ruby
#define			@ruby嗄			ruby("しゃが") 嗄 ruby
#define			@ruby跪			ruby("ひざまず") 跪 ruby
#define			@ruby靡			ruby("なび") 靡 ruby
#define			@ruby噤			ruby("つぐ") 噤 ruby
//汉化版添加部分
#define         @ruby死后世界战线    ruby("死后世界战线") "SSS" ruby
#define         @ruby没有活着的感觉     ruby("含义为“活得提心吊胆”") "没有活着的感觉" ruby
#define         @ruby婚前忧郁症     ruby("Marriage Blues") "婚前忧郁症" ruby
//引用外部注释部分
#define			@ruby注释1_格雷西家族			ruby("详情见注释1") "格雷西家族" ruby
#define			@ruby性取向 ruby("取向") "想法" ruby