/********************************************************
*														*
*					 	環境設定						*
*														*
*********************************************************/
#define		@ObjSysCF00						 60			// 壁紙
#define		_ObjSysCFBg01					  0			// 通常下地
#define		_ObjSysCFBG02					  1			// その他下地

#define		@ObjSysCF01						 61			// 下地
#define		_ObjSysCFBtn01					  1			// システムボタン
#define		_ObjSysCFBtn02					  2			// テキストボタン
#define		_ObjSysCFBtn03					  3			// サウンドボタン
#define		_ObjSysCFBtn04					  4			// ゲームを終了
#define		_ObjSysCFBtn05					  5			// タイトルに戻る
#define		_ObjSysCFBtn06					  6			// セーブ
#define		_ObjSysCFBtn07					  7			// ロード
#define		_ObjSysCFBtn08					  8			// コンフィグ
#define		_ObjSysCFBtn09					  9			// ゲームに戻る

// ----------------------------------------------------------------------------
// システム
// ----------------------------------------------------------------------------
#define		@ObjSysCF02						 62
// 下地
#define		_ObjSysCFSysBg00				  0			// システム下地
// スクリーンモード
#define		_ObjSysCFWindow01				  1			// 標準ウィンドウ
#define		_ObjSysCFWindow02				  2			// フルスクリーン
#define		_ObjSysCFWindow03				  3			// ウィンドウ設定
// 現在地表示
#define		_ObjSysCFLocation01				  4			// 表示する
#define		_ObjSysCFLocation02				  5			// 表示しない
// キャラクター演出
#define		_ObjSysCFBsFadeMode01			  6			// 通常
#define		_ObjSysCFBsFadeMode02			  7			// 高速
#define		_ObjSysCFBsFadeMode03			  8			// 瞬時
// 背景演出
#define		_ObjSysCFBgFadeMode01			  9			// 通常
#define		_ObjSysCFBgFadeMode02			 10			// 高速
#define		_ObjSysCFBgFadeMode03			 11			// 瞬時
// イベントＣＧ演出
#define		_ObjSysCFEvFadeMode01			 12			// 通常
#define		_ObjSysCFEvFadeMode02			 13			// 高速
#define		_ObjSysCFEvFadeMode03			 14			// 瞬時
// メッセージウィンドウ演出
#define		_ObjSysCFMwFadeMode01			 15			// 通常
#define		_ObjSysCFMwFadeMode02			 16			// 高速
#define		_ObjSysCFMwFadeMode03			 17			// 瞬時
// システムメニュー演出
#define		_ObjSysCFMeFadeMode01			 18			// 通常
#define		_ObjSysCFMeFadeMode02			 19			// 高速
#define		_ObjSysCFMeFadeMode03			 20			// 瞬時
// エモーション表示
#define		_ObjSysCFDSBtn01				 21			// エモーション表示ＯＮ
#define		_ObjSysCFDSBtn02				 22			// エモーション表示ＯＦＦ
// メッセージスキップ
#define		_ObjSysCFMSSkipBtn01			 23			// 既読のみ
#define		_ObjSysCFMSSkipBtn02			 24			// 未読も含む
// オートセーブ
#define		_ObjSysCFASaveBtn01				 25			// 使用する
#define		_ObjSysCFASaveBtn02				 26			// 使用しない
// 右クリック動作
#define		_ObjSysCFRClickBtn01			 27			// クイックメニュー
#define		_ObjSysCFRClickBtn02			 28			// ウィンドウ消去
#define		_ObjSysCFRClickBtn03			 29			// セーブ画面
#define		_ObjSysCFRClickBtn04			 30			// ロード画面
#define		_ObjSysCFRClickBtn05			 31			// コンフィグ画面
// 確認メッセージ
#define		_ObjSysCFConDLBtn01				 32			// セーブ／ロード
#define		_ObjSysCFConDLBtn02				 33			// クイックセーブ／クイックロード
#define		_ObjSysCFConDLBtn03				 34			// 上書きセーブ
#define		_ObjSysCFConDLBtn04				 35			// 前の選択肢に戻る
#define		_ObjSysCFConDLBtn05				 36			// セーブデータの入れ替え
#define		_ObjSysCFConDLBtn06				 37			// タイトルに戻る
#define		_ObjSysCFConDLBtn07				 38			// セーブデータの削除
#define		_ObjSysCFConDLBtn08				 39			// ゲームを終了する
// その他の設定
#define		_ObjSysCFESChk01				 40			// マウスホイールボタンの…
#define		_ObjSysCFESChk02				 41			// 本プログラムの動作を…
// ムービー設定
#define		_ObjSysCFMovSetBtn00			 42			// ムービー設定
// 実績システム（仮）
#define		_ObjSysCFResultBtn01			 43			// 表示する
#define		_ObjSysCFResultBtn02			 44			// 表示しない

// ----------------------------------------------------------------------------
// テキスト
// ----------------------------------------------------------------------------
#define		@ObjSysCF03						 63
// 下地
#define		_ObjSysCFTtBg00					 0
// フォント
#define		_ObjSysCFTtBtn01				 1			// フォントＡ
#define		_ObjSysCFTtBtn02				 2			// フォントＢ
#define		_ObjSysCFTtBtn03				 3			// フォント設定
// ノーウェイト
#define		_ObjSysCFTtChk01				 4
// メッセージ速度
#define		_ObjSysCFTtBar01				 5
#define		_ObjSysCFTtCtl01				 6
#define		_ObjSysCFTtBar01e				 7
// 初期設定に戻す
#define		_ObjSysCFTtBtn04				 9
// ウィンドウ背景[赤]
#define		_ObjSysCFTtBar02				10
#define		_ObjSysCFTtCtl02				11
#define		_ObjSysCFTtBar02e				12
// ウィンドウ背景[緑]
#define		_ObjSysCFTtBar03				13
#define		_ObjSysCFTtCtl03				14
#define		_ObjSysCFTtBar03e				15
// ウィンドウ背景[青]
#define		_ObjSysCFTtBar04				16
#define		_ObjSysCFTtCtl04				17
#define		_ObjSysCFTtBar04e				18
// ウィンドウ背景[透過度]
#define		_ObjSysCFTtBar05				19
#define		_ObjSysCFTtCtl05				20
#define		_ObjSysCFTtBar05e				21
// サンプルテキスト
#define		_ObjSysCFTtMsgBg00				22
#define		_ObjSysCFTtMsg00				23
#define		_ObjSysCFTtBtn05				24			// 初期設定に戻す
// オートモード
#define		_ObjSysCFTtChk02				25			// オートモードチェック
// 文字時間
#define		_ObjSysCFTtBar06				26
#define		_ObjSysCFTtCtl06				27
#define		_ObjSysCFTtBar06e				28
// 最小時間
#define		_ObjSysCFTtBar07				29
#define		_ObjSysCFTtCtl07				30
#define		_ObjSysCFTtBar07e				31
// 文字時間数値
#define		_ObjSysCFTtANum01				32
#define		_ObjSysCFTtANum02				33
#define		_ObjSysCFTtANum03				34
// 最小時間数値
#define		_ObjSysCFTtANum04				35
#define		_ObjSysCFTtANum05				36
#define		_ObjSysCFTtANum06				37
// 待ち時間数値
#define		_ObjSysCFTtANum07				38
#define		_ObjSysCFTtANum08				39
#define		_ObjSysCFTtANum09				40
#define		_ObjSysCFTtANum10				41
// 初期設定に戻す
#define		_ObjSysCFTtBtn06				42


// ----------------------------------------------------------------------------
// サウンド
// ----------------------------------------------------------------------------
#define		@ObjSysCF04						 64
// 下地
#define		_ObjSysCFSndBg00				  0
// 音量設定[全体]
#define		_ObjSysCFSndVolChk01			  1
#define		_ObjSysCFSndVolBar01			  2
#define		_ObjSysCFSndVolCtl01			  3
#define		_ObjSysCFSndVolBar01e			  4
// 音量設定[ＢＧＭ]
#define		_ObjSysCFSndVolChk02			  5
#define		_ObjSysCFSndVolBar02			  6
#define		_ObjSysCFSndVolCtl02			  7
#define		_ObjSysCFSndVolBar02e			  8
// 音量設定[ＢＧＭフェード]
#define		_ObjSysCFSndVolChk03			  9
#define		_ObjSysCFSndVolBar03			 10
#define		_ObjSysCFSndVolCtl03			 11
#define		_ObjSysCFSndVolBar03e			 12
// 音量設定[音声]
#define		_ObjSysCFSndVolChk04			 13
#define		_ObjSysCFSndVolBar04			 14
#define		_ObjSysCFSndVolCtl04			 15
#define		_ObjSysCFSndVolBar04e			 16
// 音量設定[効果音]
#define		_ObjSysCFSndVolChk05			 17
#define		_ObjSysCFSndVolBar05			 18
#define		_ObjSysCFSndVolCtl05			 19
#define		_ObjSysCFSndVolBar05e			 20
// 音量設定[システム音]
#define		_ObjSysCFSndVolChk06			 21
#define		_ObjSysCFSndVolBar06			 22
#define		_ObjSysCFSndVolCtl06			 23
#define		_ObjSysCFSndVolBar06e			 24
// 音量設定[ムービー]
#define		_ObjSysCFSndVolChk07			 25
#define		_ObjSysCFSndVolBar07			 26
#define		_ObjSysCFSndVolCtl07			 27
#define		_ObjSysCFSndVolBar07e			 28
// 初期設定に戻す
#define		_ObjSysCFSndVolBtn01			 29
// ボリュームテスト再生ボタン
#define		_ObjSysCFSndVolBtn02			 30			// 全体
#define		_ObjSysCFSndVolBtn03			 31			// ＢＧＭ
#define		_ObjSysCFSndVolBtn04			 32			// ＢＧＭフェード
#define		_ObjSysCFSndVolBtn05			 33			// 音声
#define		_ObjSysCFSndVolBtn06			 34			// 効果音
#define		_ObjSysCFSndVolBtn07			 35			// システム音
#define		_ObjSysCFSndVolBtn08			 36			// ムービー
// キャラクター音声の再生（声の再生中に次の文章に進んでも再生を続ける）
#define		_ObjSysCFSndVolBtn09			 37
// キャラクター別音声[ボタン]
#define		_ObjSysCFSndCVBtn01				 38			// キャラ０１[音無]
#define		_ObjSysCFSndCVBtn02				 39			// キャラ０２[ゆり]
#define		_ObjSysCFSndCVBtn03				 40			// キャラ０３[天使]
#define		_ObjSysCFSndCVBtn04				 41			// キャラ０４[日向]
#define		_ObjSysCFSndCVBtn05				 42			// キャラ０５[ユイ]
#define		_ObjSysCFSndCVBtn06				 43			// キャラ０６[岩沢]
#define		_ObjSysCFSndCVBtn07				 44			// キャラ０７[松下]
#define		_ObjSysCFSndCVBtn08				 45			// キャラ０８[野田]
#define		_ObjSysCFSndCVBtn09				 46			// キャラ０９[高松]
#define		_ObjSysCFSndCVBtn10				 47			// キャラ１０[大山]
#define		_ObjSysCFSndCVBtn11				 48			// キャラ１１[藤巻]
#define		_ObjSysCFSndCVBtn12				 49			// キャラ１２[ＴＫ]
#define		_ObjSysCFSndCVBtn13				 50			// キャラ１３[椎名]
#define		_ObjSysCFSndCVBtn14				 51			// キャラ１４[遊佐]
#define		_ObjSysCFSndCVBtn15				 52			// キャラ１５[ひさ子]
#define		_ObjSysCFSndCVBtn16				 53			// キャラ１６[関根]
#define		_ObjSysCFSndCVBtn17				 54			// キャラ１７[入江]
#define		_ObjSysCFSndCVBtn18				 55			// キャラ１８[チャー]
#define		_ObjSysCFSndCVBtn19				 56			// キャラ１９[竹山]
#define		_ObjSysCFSndCVBtn20				 57			// キャラ２０[直井]
#define		_ObjSysCFSndCVBtn21				 58			// キャラ２１[その他・男]
#define		_ObjSysCFSndCVBtn22				 59			// キャラ２２[その他・女]
// キャラクター別音声[テスト再生]
#define		_ObjSysCFSndCVTestPlay01		 60			// キャラ０１[音無]
#define		_ObjSysCFSndCVTestPlay02		 61			// キャラ０２[ゆり]
#define		_ObjSysCFSndCVTestPlay03		 62			// キャラ０３[天使]
#define		_ObjSysCFSndCVTestPlay04		 63			// キャラ０４[日向]
#define		_ObjSysCFSndCVTestPlay05		 64			// キャラ０５[ユイ]
#define		_ObjSysCFSndCVTestPlay06		 65			// キャラ０６[岩沢]
#define		_ObjSysCFSndCVTestPlay07		 66			// キャラ０７[松下]
#define		_ObjSysCFSndCVTestPlay08		 67			// キャラ０８[野田]
#define		_ObjSysCFSndCVTestPlay09		 68			// キャラ０９[高松]
#define		_ObjSysCFSndCVTestPlay10		 69			// キャラ１０[大山]
#define		_ObjSysCFSndCVTestPlay11		 70			// キャラ１１[藤巻]
#define		_ObjSysCFSndCVTestPlay12		 71			// キャラ１２[ＴＫ]
#define		_ObjSysCFSndCVTestPlay13		 72			// キャラ１３[椎名]
#define		_ObjSysCFSndCVTestPlay14		 73			// キャラ１４[遊佐]
#define		_ObjSysCFSndCVTestPlay15		 74			// キャラ１５[ひさ子]
#define		_ObjSysCFSndCVTestPlay16		 75			// キャラ１６[関根]
#define		_ObjSysCFSndCVTestPlay17		 76			// キャラ１７[入江]
#define		_ObjSysCFSndCVTestPlay18		 77			// キャラ１８[チャー]
#define		_ObjSysCFSndCVTestPlay19		 78			// キャラ１９[竹山]
#define		_ObjSysCFSndCVTestPlay20		 79			// キャラ２０[直井]
#define		_ObjSysCFSndCVTestPlay21		 80			// キャラ２１[その他・男]
#define		_ObjSysCFSndCVTestPlay22		 81			// キャラ２２[その他・女]
// キャラクター別音声[ボリュームバー]
#define		_ObjSysCFSndCVBar01				 82			// キャラ０１[音無]
#define		_ObjSysCFSndCVBar02				 83			// キャラ０２[ゆり]
#define		_ObjSysCFSndCVBar03				 84			// キャラ０３[天使]
#define		_ObjSysCFSndCVBar04				 85			// キャラ０４[日向]
#define		_ObjSysCFSndCVBar05				 86			// キャラ０５[ユイ]
#define		_ObjSysCFSndCVBar06				 87			// キャラ０６[岩沢]
#define		_ObjSysCFSndCVBar07				 88			// キャラ０７[松下]
#define		_ObjSysCFSndCVBar08				 89			// キャラ０８[野田]
#define		_ObjSysCFSndCVBar09				 90			// キャラ０９[高松]
#define		_ObjSysCFSndCVBar10				 91			// キャラ１０[大山]
#define		_ObjSysCFSndCVBar11				 92			// キャラ１１[藤巻]
#define		_ObjSysCFSndCVBar12				 93			// キャラ１２[ＴＫ]
#define		_ObjSysCFSndCVBar13				 94			// キャラ１３[椎名]
#define		_ObjSysCFSndCVBar14				 95			// キャラ１４[遊佐]
#define		_ObjSysCFSndCVBar15				 96			// キャラ１５[ひさ子]
#define		_ObjSysCFSndCVBar16				 97			// キャラ１６[関根]
#define		_ObjSysCFSndCVBar17				 98			// キャラ１７[入江]
#define		_ObjSysCFSndCVBar18				 99			// キャラ１８[チャー]
#define		_ObjSysCFSndCVBar19				100			// キャラ１９[竹山]
#define		_ObjSysCFSndCVBar20				101			// キャラ２０[直井]
#define		_ObjSysCFSndCVBar21				102			// キャラ２１[その他・男]
#define		_ObjSysCFSndCVBar22				103			// キャラ２２[その他・女]
// キャラクター別音声[ボリュームＣＴＬ]
#define		_ObjSysCFSndCVCtrl01			104			// キャラ０１[音無]
#define		_ObjSysCFSndCVCtrl02			105			// キャラ０２[ゆり]
#define		_ObjSysCFSndCVCtrl03			106			// キャラ０３[天使]
#define		_ObjSysCFSndCVCtrl04			107			// キャラ０４[日向]
#define		_ObjSysCFSndCVCtrl05			108			// キャラ０５[ユイ]
#define		_ObjSysCFSndCVCtrl06			109			// キャラ０６[岩沢]
#define		_ObjSysCFSndCVCtrl07			110			// キャラ０７[松下]
#define		_ObjSysCFSndCVCtrl08			111			// キャラ０８[野田]
#define		_ObjSysCFSndCVCtrl09			112			// キャラ０９[高松]
#define		_ObjSysCFSndCVCtrl10			113			// キャラ１０[大山]
#define		_ObjSysCFSndCVCtrl11			114			// キャラ１１[藤巻]
#define		_ObjSysCFSndCVCtrl12			115			// キャラ１２[ＴＫ]
#define		_ObjSysCFSndCVCtrl13			116			// キャラ１３[椎名]
#define		_ObjSysCFSndCVCtrl14			117			// キャラ１４[遊佐]
#define		_ObjSysCFSndCVCtrl15			118			// キャラ１５[ひさ子]
#define		_ObjSysCFSndCVCtrl16			119			// キャラ１６[関根]
#define		_ObjSysCFSndCVCtrl17			120			// キャラ１７[入江]
#define		_ObjSysCFSndCVCtrl18			121			// キャラ１８[チャー]
#define		_ObjSysCFSndCVCtrl19			122			// キャラ１９[竹山]
#define		_ObjSysCFSndCVCtrl20			123			// キャラ２０[直井]
#define		_ObjSysCFSndCVCtrl21			124			// キャラ２１[その他・男]
#define		_ObjSysCFSndCVCtrl22			125			// キャラ２２[その他・女]
// キャラクター別音声[ボリュームＣＴＬ] -Clip
#define		_ObjSysCFSndCVBar01e			126			// キャラ０１[音無]
#define		_ObjSysCFSndCVBar02e			127			// キャラ０２[ゆり]
#define		_ObjSysCFSndCVBar03e			128			// キャラ０３[天使]
#define		_ObjSysCFSndCVBar04e			129			// キャラ０４[日向]
#define		_ObjSysCFSndCVBar05e			130			// キャラ０５[ユイ]
#define		_ObjSysCFSndCVBar06e			131			// キャラ０６[岩沢]
#define		_ObjSysCFSndCVBar07e			132			// キャラ０７[松下]
#define		_ObjSysCFSndCVBar08e			133			// キャラ０８[野田]
#define		_ObjSysCFSndCVBar09e			134			// キャラ０９[高松]
#define		_ObjSysCFSndCVBar10e			135			// キャラ１０[大山]
#define		_ObjSysCFSndCVBar11e			136			// キャラ１１[藤巻]
#define		_ObjSysCFSndCVBar12e			137			// キャラ１２[ＴＫ]
#define		_ObjSysCFSndCVBar13e			138			// キャラ１３[椎名]
#define		_ObjSysCFSndCVBar14e			139			// キャラ１４[遊佐]
#define		_ObjSysCFSndCVBar15e			140			// キャラ１５[ひさ子]
#define		_ObjSysCFSndCVBar16e			141			// キャラ１６[関根]
#define		_ObjSysCFSndCVBar17e			142			// キャラ１７[入江]
#define		_ObjSysCFSndCVBar18e			143			// キャラ１８[チャー]
#define		_ObjSysCFSndCVBar19e			144			// キャラ１９[竹山]
#define		_ObjSysCFSndCVBar20e			145			// キャラ２０[直井]
#define		_ObjSysCFSndCVBar21e			146			// キャラ２１[その他・男]
#define		_ObjSysCFSndCVBar22e			147			// キャラ２２[その他・女]
// キャラクター音声の再生
#define		_ObjSysCFSndVolBtn10			148			// 全てＯＮ
#define		_ObjSysCFSndVolBtn11			149			// 全てＯＦＦ
// 初期設定に戻す
#define		_ObjSysCFSndVolBtn12			150

// 確認メッセージ	todo 修正
#define		@ObjSysCF05					    65
#define		_ObjSysCFConfBg00			     0			// 確認メッセージ下地
#define		_ObjSysCFConfBtn01			     1			// ボタン[ＹＥＳ]
#define		_ObjSysCFConfBtn02			     2			// ボタン[ＮＯ]
#define		_ObjSysCFConfChk00			     3			// 確認ダイアログ
#define		_ObjSysCFConfFilter00		     4			// フィルター

// フェードアウト
#define		@ObjSysCF06					    66
#define		_ObjSysCFFade00				     0

// ----------------------------------------------------------------------------
// 環境設定関連フラグ
// ----------------------------------------------------------------------------
#define		@SysCFPage							$sys_cf_page
#define		@SysCFLastPage						$sys_cf_page_last
#define		@SysCFPagePrev						$sys_cf_page_prev
#define		@WWSizeState						$ww_size_state		// ゲームウィンドウ
#define		@WWSizeStatePrev					$ww_size_state_prev	// ゲームウィンドウ
#define		@SpotDispState						G[1300]				
#define		@BsFadeState						G[1301]				// キャラクター表示演出
#define		@BgFadeState						G[1302]				// 背景表示演出
#define		@EvFadeState						G[1303]				// イベントＣＧ表示演出
#define		@MwFadeState						G[1304]				// メッセージウィンドウ表示演出
#define		@MeFadeState						G[1305]				// システムメニュー表示演出
#define		@EmDispState						G[1306]				// エモ表示演出
#define		@MsgSkipState						$msg_skip_state		// メッセージスキップ
#define		@MRActionState						G[1307]				// 右クリック動作
#define		@AllChkState						$all_chk_state		// 全て ＯＮ／ＯＦＦ
#define		@AllVolState						$all_vol_state		// 全てボリューム
#define		@BgmChkState						$bgm_chk_state		// ＢＧＭ ＯＮ／ＯＦＦ
#define		@BgmVolState						$bgm_vol_state		// ＢＧＭボリューム
#define		@VoiceChkState						$voice_chk_state	// 音声 ＯＮ／ＯＦＦ
#define		@VoiceTChkState						$voice_tchk_state	// 音声のみ再生
#define		@VoiceVolState						$voice_vol_state	// 音声ボリューム
#define		@BFadeChk01State					$bfade_chk01_state	// ＢＧＭフェード ＯＮ／ＯＦＦ
#define		@BFadeVolState						$bfade_vol_state	// ＢＧＭフェードボリューム
#define		@SeChkState							$se_chk_state		// ＳＥ ＯＮ／ＯＦＦ
#define		@SeVolState							$se_vol_state		// ＳＥボリューム
#define		@SysChkState						$sys_chk_state		// システム音 ＯＮ／ＯＦＦ
#define		@SysVolState						$sys_vol_state		// システム音ボリューム
#define		@MovChkState						$mov_chk_state		// ムービー音 ＯＮ／ＯＦＦ
#define		@MovVolState						$mov_vol_state		// ムービー音ボリューム
#define		@CVSwitch							$cv_switch			// キャラクター音声 ＯＮ／ＯＦＦ
#define		@CVState[							$cv_state[			// キャラ音声
#define		@CVState01							$cv_state[0]		// キャラ０１音声[音無]
#define		@CVState02							$cv_state[1]		// キャラ０２音声[ゆり]
#define		@CVState03							$cv_state[2]		// キャラ０３音声[天使]
#define		@CVState04							$cv_state[3]		// キャラ０４音声[日向]
#define		@CVState05							$cv_state[4]		// キャラ０５音声[ユイ]
#define		@CVState06							$cv_state[5]		// キャラ０６音声[岩沢]
#define		@CVState07							$cv_state[6]		// キャラ０７音声[松下]
#define		@CVState08							$cv_state[7]		// キャラ０８音声[野田]
#define		@CVState09							$cv_state[8]		// キャラ０９音声[高松]
#define		@CVState10							$cv_state[9]		// キャラ１０音声[大山]
#define		@CVState11							$cv_state[10]		// キャラ１１音声[藤巻]
#define		@CVState12							$cv_state[11]		// キャラ１２音声[ＴＫ]
#define		@CVState13							$cv_state[12]		// キャラ１３音声[椎名]
#define		@CVState14							$cv_state[13]		// キャラ１４音声[遊佐]
#define		@CVState15							$cv_state[14]		// キャラ１５音声[ひさ子]
#define		@CVState16							$cv_state[15]		// キャラ１５音声[関根]
#define		@CVState17							$cv_state[16]		// キャラ１５音声[入江]
#define		@CVState18							$cv_state[17]		// キャラ１５音声[チャー]
#define		@CVState19							$cv_state[18]		// キャラ１５音声[竹山]
#define		@CVState20							$cv_state[19]		// キャラ１５音声[直井]
#define		@CVState21							$cv_state[20]		// キャラ１５音声[その他・男]
#define		@CVState22							$cv_state[21]		// キャラ１５音声[その他・女]
#define		@CVVolState[						$cv_vol_state[		// キャラ音声ボリューム
#define		@CVVolState01						$cv_vol_state[0]	// キャラ０１音声ボリューム[音無]
#define		@CVVolState02						$cv_vol_state[1]	// キャラ０２音声ボリューム[ゆり]
#define		@CVVolState03						$cv_vol_state[2]	// キャラ０３音声ボリューム[天使]
#define		@CVVolState04						$cv_vol_state[3]	// キャラ０４音声ボリューム[日向]
#define		@CVVolState05						$cv_vol_state[4]	// キャラ０５音声ボリューム[ユイ]
#define		@CVVolState06						$cv_vol_state[5]	// キャラ０６音声ボリューム[岩沢]
#define		@CVVolState07						$cv_vol_state[6]	// キャラ０７音声ボリューム[松下]
#define		@CVVolState08						$cv_vol_state[7]	// キャラ０８音声ボリューム[野田]
#define		@CVVolState09						$cv_vol_state[8]	// キャラ０９音声ボリューム[高松]
#define		@CVVolState10						$cv_vol_state[9]	// キャラ１０音声ボリューム[大山]
#define		@CVVolState11						$cv_vol_state[10]	// キャラ１１音声ボリューム[藤巻]
#define		@CVVolState12						$cv_vol_state[11]	// キャラ１２音声ボリューム[ＴＫ]
#define		@CVVolState13						$cv_vol_state[12]	// キャラ１３音声ボリューム[椎名]
#define		@CVVolState14						$cv_vol_state[13]	// キャラ１４音声ボリューム[遊佐]
#define		@CVVolState15						$cv_vol_state[14]	// キャラ１５音声ボリューム[ひさ子]
#define		@CVVolState16						$cv_vol_state[15]	// キャラ１６音声ボリューム[関根]
#define		@CVVolState17						$cv_vol_state[16]	// キャラ１７音声ボリューム[入江]
#define		@CVVolState18						$cv_vol_state[17]	// キャラ１８音声ボリューム[チャー]
#define		@CVVolState19						$cv_vol_state[18]	// キャラ１９音声ボリューム[竹山]
#define		@CVVolState20						$cv_vol_state[19]	// キャラ２０音声ボリューム[直井]
#define		@CVVolState21						$cv_vol_state[20]	// キャラ２１音声ボリューム[その他・男]
#define		@CVVolState22						$cv_vol_state[21]	// キャラ２２音声ボリューム[その他・女]
#define		@MSChkState							$ms_chk_state		// メッセージスピードＣｔｒｌ
#define		@MSState							$mss_state			// メッセージスピード状態
#define		@WBState01							$wb_state01			// ＭＳＧ背景 Ｒ
#define		@WBState02							$wb_state02			// ＭＳＧ背景 Ｇ
#define		@WBState03							$wb_state03			// ＭＳＧ背景 Ｂ
#define		@WBState04							$wb_state04			// ＭＳＧ背景 TR
#define		@WBChkState							$wb_chkstate		// ＭＳＧフィルターモード
#define		@EsState[							$es_state[
#define		@EsState[0]							$es_state[0]		// 本プログラムの動作…チェック
#define		@EsState[1]							$es_state[1]		// メッセージウィンドウの開閉時のアニメを無効にする
#define		@EsState[2]							$es_state[2]		// 画面暗転時の効果を……チェック
#define		@EsState[3]							$es_state[3]		// マウスのホイール…チェック
#define		@EsState[4]							$es_state[4]		// 声の再生時に…チェック
#define		@EsState[5]							$es_state[5]		// オートセーブを有効化にする…チェック
#define		@EsState[6]							$es_state[6]		// 項目の簡易説明を表示する…チェック
#define		@EsState[7]							$es_state[7]		// 選択肢でオートモードを解除する…チェック
#define		@EsState[8]							$es_state[8]		// 選択肢でスキップモードを解除する…チェック
#define		@EsState[9]							$es_state[9]		// 再生されるＢＧＭの詳細を表示する…チェック
#define		@EsState[10]						$es_state[10]		// サウンドの再生時に…
#define		@EsState[11]						$es_state[11]		// その他の設定・予備
#define		@EsState[12]						$es_state[12]		// その他の設定・予備
#define		@EsState[13]						$es_state[13]		// その他の設定・予備
#define		@EsState[14]						$es_state[14]		// その他の設定・予備
#define		@SVState							G[1310]				// システム音声
#define		@SysCFPageCSpd						$sys_cfpage_cspd	// 環境設定ページ切り替え速度
#define		@CVSwitchState						G[1311]				// キャラクター音声スイッチ
#define		@BgFadeMode							G[1312]				// 
#define		@BsFadeMode							G[1313]				// 
#define		@EvFadeMode							G[1314]				// 
#define		@MeFadeMode							G[1315]				// 
#define		@CdState[							G[1316
#define		@CdStateReady						$cd_state_ready		// 次回以降この確認を行わない
#define		@EsAutoSave							G[1330]				// オートセーブを有効化
#define		@EsExplainDisp						G[1331]				// 項目の簡易説明を表示する
#define		@EsSelAutoReset						G[1332]				// 選択肢でオートモードを解除する
#define		@EsSelSkipReset						G[1333]				// 選択肢でスキップモードを解除する
#define		@EsBgmDetailDisp					G[1334]				// 再生されるＢＧＭの詳細を表示する
#define		@EsBgmDetailDispPrev				G[1335]				// 再生されるＢＧＭの詳細を表示する
#define		@CNoLSW								0					// ＜-CountNo
#define		@CNoLCtrl							1					// ＜-CTL移動負荷CountNo
#define		@CNoRSW								2					// -＞CountNo
#define		@CNoRCtrl							3					// -＞CTL移動負荷CountNo
#define		@CNoMSP01							4					// メッセージスピード用カウンター０１
#define		@CNoMSP02							5					// メッセージスピード用カウンター０２
#define		@CNoBgmTest							6					// ＢＧＭテスト再生用
#define		@CNoGen01							8					// 汎用01
#define		@CNoGen02							9					// 汎用01

#define		@SysCFhelpDisp						$sys_cf_help_disp

#define		@SysCFPageChange					$sys_cfpage_change	// ページ切り替え判定
#property	$sys_cfpage_change : int

// オートモード
#define		@AmCheckState						$amcheckstate
#define		@TTimeState							$ttimestate
#define		@StimeState							$stimestate
#define		@CheckDefState						$checkdefstate
#define		@TTimeDefState						$ttimedefstate
#define		@StimeDefState						$stimedefstate

#property	$amcheckstate          : int
#property	$ttimestate            : int
#property	$stimestate            : int
#property	$checkdefstate         : int
#property	$ttimedefstate         : int
#property	$stimedefstate         : int


#property	$sys_cf_page           : int
#property	$sys_cf_page_last      : int
#property	$sys_cf_page_prev      : int
#property	$ww_size_state         : int
#property	$ww_size_state_prev    : int
#property	$bg_fade_state         : int
#property	$bs_fade_state         : int
#property	$ev_fade_state         : int
#property	$me_fade_state         : int
#property	$em_disp_state         : int
#property	$msg_skip_state        : int
#property	$All_chk_state         : int
#property	$All_vol_state         : int
#property	$bgm_chk_state         : int
#property	$bgm_vol_state         : int
#property	$voice_chk_state       : int
#property	$voice_tchk_state      : int
#property	$voice_vol_state       : int
#property	$bfade_chk01_state     : int
#property	$bfade_vol_state       : int
#property	$se_chk_state          : int
#property	$se_vol_state          : int
#property	$sys_chk_state         : int
#property	$sys_vol_state         : int
#property	$mov_chk_state         : int
#property	$mov_vol_state         : int

#property	$cv_state              : intlist[30]
#property	$cv_vol_state          : intlist[30]
#property	$ms_chk_state          : int
#property	$mss_state             : int
#property	$wb_state01            : int
#property	$wb_state02            : int
#property	$wb_state03            : int
#property	$wb_state04            : int
#property	$wb_chkstate           : int
#property	$es_state              : intlist[30]
#property	$sys_cfpage_cspd       : int
#property	$cd_state_ready        : int

#property	$sys_cf_help_disp      : int

/****************************************************************
*		 スライダーの座標は毎ゲームごとに設定すること 			*
*		 番号は基本的に固定だが、毎回必ず確認すること 			*
*****************************************************************/
#define		@S_CTL_BAR_POS						$s_ctl_bar_pos
#define		@S_CTL_BAR							$s_ctl_bar
#define		@S_CTL_LBTN_ACTIVE					$s_ctl_lbtn_active
#define		@S_CTL_RBTN_ACTIVE					$s_ctl_rbtn_active
#define		@S_CTL_BAR_STPOS					$s_ctl_bar_stpos
#define		@S_CTL_BAR_EDPOS					$s_ctl_bar_edpos
#define		@S_CTL_BAR_ACTIVE					$s_ctl_bar_active
#define		@S_CTL_BAR_CTLPOS					$s_ctl_bar_ctlpos
#define		@S_CTL_BAR_CTLACTIVE				$s_ctl_bar_ctlactive
#define		@S_CTL_BAR_OBJSTATE					$s_ctl_bar_objstate
#define		@S_CTL_BAR_CTLSTATE					$s_ctl_bar_ctlstate
#define		@S_CTL_BAR_LBTNSTATE				$s_ctl_bar_lbtnstate
#define		@S_CTL_BAR_RBTNSTATE				$s_ctl_bar_rbtnstate
#define		@S_CTL_BAR_BARSTATE					$s_ctl_bar_barstate
#define		@S_CTL_BAR_CTLPOS_PREV				$s_ctl_bar_ctlpos_prev
#define		@S_CTL_BAR_SET						$s_ctl_bar_set
#define		@MSP_SET							$msp_set
#define		@MSP_SET_PREV						$msp_set_prev
#define		@WB_R_SET							$wb_r_set
#define		@WB_G_SET							$wb_g_set
#define		@WB_B_SET							$wb_b_set
#define		@WB_TR_SET							$wb_tr_set
#define		@MSP_CTL_BAR_SET					$msp_ctl_bar_set
#define		@S_CTL_BAR_SET_PREV					$s_ctl_bar_set_prev
#define		@MSP_CTL_BAR_SET_PREV				$msp_ctl_bar_set_prev
#define		@MSP_TOUCH_STATE01					$msp_touch_state01
#define		@MSP_TOUCH_STATE02					$msp_touch_state02
#define		@MSP_TOUCH_STATE03					$msp_touch_state03
#define		@MS_POSE_TEST_STATE					$ms_pose_test_state
#define		@MS_POSE_DELAY_STATE				$ms_pose_delay_state
#property	$s_ctl_bar_pos         : int
#property	$s_ctl_bar             : int
#property	$s_ctl_lbtn_active     : int
#property	$s_ctl_rbtn_active     : int
#property	$s_ctl_bar_stpos       : int
#property	$s_ctl_bar_edpos       : int
#property	$s_ctl_bar_active      : int
#property	$s_ctl_bar_ctlpos      : int
#property	$s_ctl_bar_ctlactive   : int
#property	$s_ctl_bar_objstate    : int
#property	$s_ctl_bar_ctlstate    : int
#property	$s_ctl_bar_lbtnstate   : int
#property	$s_ctl_bar_rbtnstate   : int
#property	$s_ctl_bar_barstate    : int
#property	$s_ctl_bar_ctlpos_prev : int
#property	$s_ctl_bar_set         : int
#property	$msp_set               : int
#property	$msp_set_prev          : int
#property	$wb_r_set              : int
#property	$wb_g_set              : int
#property	$wb_b_set              : int
#property	$wb_tr_set             : int
#property	$msp_ctl_bar_set       : int
#property	$s_ctl_bar_set_prev    : int
#property	$msp_ctl_bar_set_prev  : int
#property	$msp_touch_state01     : int
#property	$msp_touch_state02     : int
#property	$msp_touch_state03     : int
#property	$ms_pose_test_state    : int
#property	$ms_pose_delay_state   : int
#property	$s_ctr_bar_pos_defult  : int
#property	$ttime_set             : int
#property	$stime_set             : int
#property	$wtime_set             : int

// スライダーバー[デフォルト]
#define		@S_CTR_BAR_POS_DEFULT00			     $s_ctr_bar_pos_defult
// メッセージスピード
#define		@S_CTL_BAR_MS_STPOS					 284
#define		@S_CTL_BAR_MS_EDPOS					 549
// ウィンドウ背景[赤]
#define		@S_CTL_BAR_MWBG_STPOS01				 284
#define		@S_CTL_BAR_MWBG_EDPOS01				 549
// ウィンドウ背景[緑]
#define		@S_CTL_BAR_MWBG_STPOS02				 284
#define		@S_CTL_BAR_MWBG_EDPOS02				 549
// ウィンドウ背景[青]
#define		@S_CTL_BAR_MWBG_STPOS03				 284
#define		@S_CTL_BAR_MWBG_EDPOS03				 549
// ウィンドウ背景[透過度]
#define		@S_CTL_BAR_MWBG_STPOS04				 284
#define		@S_CTL_BAR_MWBG_EDPOS04				 549
// 文字時間
#define		@S_CTL_BAR_TTIME_STPOS				 948
#define		@S_CTL_BAR_TTIME_EDPOS				1158
#define		@TTIME_SET							$ttime_set
// 最小時間
#define		@S_CTL_BAR_STIME_STPOS				 948
#define		@S_CTL_BAR_STIME_EDPOS				1158
#define		@STIME_SET							$stime_set
// 待ち時間
#define		@WTIME_SET							$wtime_set
// 音量設定[全体]
#define		@S_CTL_BAR_VOL_ALL_STPOS			 265
#define		@S_CTL_BAR_VOL_ALL_EDPOS			 530
// 音量設定[ＢＧＭ]
#define		@S_CTL_BAR_VOL_BGM_STPOS			 265
#define		@S_CTL_BAR_VOL_BGM_EDPOS			 530
// 音量設定[音声]
#define		@S_CTL_BAR_VOL_VOICE_STPOS			 265
#define		@S_CTL_BAR_VOL_VOICE_EDPOS			 530
// 音量設定[ＢＧＭフェード]
#define		@S_CTL_BAR_VOL_BFADE_STPOS			 265
#define		@S_CTL_BAR_VOL_BFADE_EDPOS			 530
// 音量設定[ＳＥ]
#define		@S_CTL_BAR_VOL_SE_STPOS				 265
#define		@S_CTL_BAR_VOL_SE_EDPOS				 530
// 音量設定[システム]
#define		@S_CTL_BAR_VOL_SYS_STPOS			 265
#define		@S_CTL_BAR_VOL_SYS_EDPOS			 530
// 音量設定[ムービー]
#define		@S_CTL_BAR_VOL_MOV_STPOS			 265
#define		@S_CTL_BAR_VOL_MOV_EDPOS			 530

// キャラ０１[音無]
#define		@S_CTL_BAR_CV01_STPOS				  701
#define		@S_CTL_BAR_CV01_EDPOS				  775
// キャラ０２[ゆり]
#define		@S_CTL_BAR_CV02_STPOS				  789
#define		@S_CTL_BAR_CV02_EDPOS				  863
// キャラ０３[天使]
#define		@S_CTL_BAR_CV03_STPOS				  877
#define		@S_CTL_BAR_CV03_EDPOS				  951
// キャラ０４[日向]
#define		@S_CTL_BAR_CV04_STPOS				  965
#define		@S_CTL_BAR_CV04_EDPOS				 1039
// キャラ０５[ユイ]
#define		@S_CTL_BAR_CV05_STPOS				 1053
#define		@S_CTL_BAR_CV05_EDPOS				 1127
// キャラ０６[岩沢]
#define		@S_CTL_BAR_CV06_STPOS				 1141
#define		@S_CTL_BAR_CV06_EDPOS				 1215
// キャラ０７[松下]
#define		@S_CTL_BAR_CV07_STPOS				  701
#define		@S_CTL_BAR_CV07_EDPOS				  775
// キャラ０８[野田]
#define		@S_CTL_BAR_CV08_STPOS				  789
#define		@S_CTL_BAR_CV08_EDPOS				  863
// キャラ０９[高松]
#define		@S_CTL_BAR_CV09_STPOS				  877
#define		@S_CTL_BAR_CV09_EDPOS				  951
// キャラ１０[大山]
#define		@S_CTL_BAR_CV10_STPOS				  965
#define		@S_CTL_BAR_CV10_EDPOS				 1039
// キャラ１１[藤巻]
#define		@S_CTL_BAR_CV11_STPOS				 1053
#define		@S_CTL_BAR_CV11_EDPOS				 1127
// キャラ１２[ＴＫ]
#define		@S_CTL_BAR_CV12_STPOS				 1141
#define		@S_CTL_BAR_CV12_EDPOS				 1215
// キャラ１３[椎名]
#define		@S_CTL_BAR_CV13_STPOS				  701
#define		@S_CTL_BAR_CV13_EDPOS				  775
// キャラ１４[遊佐]
#define		@S_CTL_BAR_CV14_STPOS				  789
#define		@S_CTL_BAR_CV14_EDPOS				  863
// キャラ１５[ひさ子]
#define		@S_CTL_BAR_CV15_STPOS				  877
#define		@S_CTL_BAR_CV15_EDPOS				  951
// キャラ１６[関根]
#define		@S_CTL_BAR_CV16_STPOS				  965
#define		@S_CTL_BAR_CV16_EDPOS				 1039
// キャラ１７[入江]
#define		@S_CTL_BAR_CV17_STPOS				 1053
#define		@S_CTL_BAR_CV17_EDPOS				 1127
// キャラ１８[チャー]
#define		@S_CTL_BAR_CV18_STPOS				 1141
#define		@S_CTL_BAR_CV18_EDPOS				 1215
// キャラ１９[竹山]
#define		@S_CTL_BAR_CV19_STPOS				  701
#define		@S_CTL_BAR_CV19_EDPOS				  775
// キャラ２０[直井]
#define		@S_CTL_BAR_CV20_STPOS				  789
#define		@S_CTL_BAR_CV20_EDPOS				  863
// キャラ２１[その他・男]
#define		@S_CTL_BAR_CV21_STPOS				  877
#define		@S_CTL_BAR_CV21_EDPOS				  951
// キャラ２２[その他・女]
#define		@S_CTL_BAR_CV22_STPOS				  965
#define		@S_CTL_BAR_CV22_EDPOS				 1039


// スライダーオブジェクト番号
#macro		@S_CTL_BAR_OBJNUM(@Num)
			@S_CTL_BAR_OBJSTATE =@Num
// ＣＴＬ番号
#macro		@S_CTL_BAR_CTLNUM(@Num)
			@S_CTL_BAR_CTLSTATE =@Num
// ＜-番号
#macro		@S_CTL_BAR_LBTNNUM(@Num)
			@S_CTL_BAR_LBTNSTATE = @Num
// -＞番号
#macro		@S_CTL_BAR_RBTNNUM(@Num)
			@S_CTL_BAR_RBTNSTATE = @Num
// ＢＥＲ番号
#macro		@S_CTL_BAR_BARNUM(@Num)
			@S_CTL_BAR_BARSTATE = @Num
// 画面モード状態取得
#macro		@GetWindowState(@Window)
			@Window = syscom.get_window_mode
// 画面効果状態取得
//#macro		@GetEffectState(@USE)
//			@USE = GET_SYSTEM_FLAG_WEATHERUSE
// 演出状態取得
#macro		@GetDispState(@Bg, @Bs, @Ev, @Menu, @Emo)
			@BgFadeState = @Bg
			@BsFadeState = @Bs
			@EvFadeState = @Ev
			@MeFadeState = @Menu
			@EmDispState = @Emo
// メッセージスキップ状態取得
#macro		@GetMsgSkipState(@MsgSkip)
			@MsgSkip = syscom.get_skip_unread_message_onoff

// 右クリック動作
//#macro		@GetMRActionState(@MRAction)
//			@MRAction = @MRActionState

#define		@FontA			"KaiGenSP"
#define		@FontB			"QingYuanSP"
#define		@UseFontState	$use_font
#property	$use_font : str

// 現在の使用フォント取得
#macro		@GetUseFont(@UseFont)
			@UseFont = syscom.get_font_name

// 使用フォントの初期化
#define		@SetUseFontDefault
			syscom.set_font_name(@FontA)
			syscom.set_font_bold_default
			syscom.set_font_decoration_default


// 音量設定初期化
#define		@SetMusicStateDefault
			syscom.set_all_volume_default     syscom.set_all_onoff_default
			syscom.set_bgm_volume_default     syscom.set_bgm_onoff_default
			syscom.set_koe_volume_default     syscom.set_koe_onoff_default
			                                  syscom.set_koemode_default
			syscom.set_bgmfade_volume_default syscom.set_bgmfade_onoff_default
			syscom.set_pcm_volume_default     syscom.set_pcm_onoff_default
			syscom.set_se_volume_default      syscom.set_se_onoff_default
			syscom.set_mov_volume_default     syscom.set_mov_onoff_default
			@GetMusicState(@AllChkState, @AllVolState, @BgmChkState, @BgmVolState, @VoiceChkState, @VoiceTChkState, @VoiceVolState, @BFadeChk01State, @BFadeVolState, @SeChkState, @SeVolState, @SysChkState, @SysVolState, @MovChkState, @MovVolState)
			// チェック
			@AllChkState     = syscom.get_all_onoff
			@BgmChkState     = syscom.get_bgm_onoff
			@VoiceChkState   = syscom.get_koe_onoff
			@VoiceTChkState  = syscom.get_koemode
			@BFadeChk01State = syscom.get_bgmfade_onoff
			@SeChkState      = syscom.get_pcm_onoff
			@SysChkState     = syscom.get_se_onoff
			@MovChkState     = syscom.get_mov_onoff
			@MovVolState     = syscom.get_mov_volume

// キャラクター音声
#macro		@SetCVoiceStateAll(@State)
			for ($sys_forlc0 = 0, $sys_forlc0 < @cha_maxenter, $sys_forlc0 += 1)	{
				if (@State == @On)	{
					syscom.set_charakoe_onoff_default($sys_forlc0)
				}
				else	{
					syscom.set_charakoe_onoff($sys_forlc0, @State)
				}
			}

// キャラクター音声設定初期化
#define		@SetCVoiceStateDefault
			for ($sys_forlc0 = 0, $sys_forlc0 < @cha_maxenter, $sys_forlc0 += 1)	{
				syscom.set_charakoe_onoff_default($sys_forlc0)
				syscom.set_charakoe_volume_default($sys_forlc0)
			}
			@GetCVoiceVolState(@CVVolState01, @CVVolState02, @CVVolState03, @CVVolState04, @CVVolState05, @CVVolState06, @CVVolState07, @CVVolState08, @CVVolState09, @CVVolState10, @CVVolState11, @CVVolState12, @CVVolState13, @CVVolState14, @CVVolState15, @CVVolState16, @CVVolState17, @CVVolState18, @CVVolState19, @CVVolState20, @CVVolState21, @CVVolState22)
			// チェック
			@CVState01 = syscom.get_charakoe_onoff(001)	// 音無
			@CVState02 = syscom.get_charakoe_onoff(002)	// ゆり
			@CVState03 = syscom.get_charakoe_onoff(003)	// 天使
			@CVState04 = syscom.get_charakoe_onoff(004)	// 日向
			@CVState05 = syscom.get_charakoe_onoff(005)	// ユイ
			@CVState06 = syscom.get_charakoe_onoff(006)	// 岩沢
			@CVState07 = syscom.get_charakoe_onoff(007)	// 松下
			@CVState08 = syscom.get_charakoe_onoff(008)	// 野田
			@CVState09 = syscom.get_charakoe_onoff(009)	// 高松
			@CVState10 = syscom.get_charakoe_onoff(010)	// 大山
			@CVState11 = syscom.get_charakoe_onoff(011)	// 藤巻
			@CVState12 = syscom.get_charakoe_onoff(012)	// ＴＫ
			@CVState13 = syscom.get_charakoe_onoff(013)	// 椎名
			@CVState14 = syscom.get_charakoe_onoff(014)	// 遊佐
			@CVState15 = syscom.get_charakoe_onoff(015)	// ひさ子
			@CVState16 = syscom.get_charakoe_onoff(016)	// 関根
			@CVState17 = syscom.get_charakoe_onoff(017)	// 入江
			@CVState18 = syscom.get_charakoe_onoff(018)	// チャー
			@CVState19 = syscom.get_charakoe_onoff(019)	// 竹山
			@CVState20 = syscom.get_charakoe_onoff(020)	// 直井
			@CVState21 = syscom.get_charakoe_onoff(021)	// その他・男
			@CVState22 = syscom.get_charakoe_onoff(022)	// その他・女

// ＢＧＭ・音声状態取得
#macro		@GetMusicState(@AllChk, @AllVol, @BgmChk, @BgmVol, @VoiceChk, @VoiceTChk, @VoiceVol, @VFadeChk01, @VFadeVol, @SeChk, @SeVol, @SysChk, @SysVol, @MovChk, @MovVol)
			@AllChk    = syscom.get_all_onoff
			@AllVol    = syscom.get_all_volume
			@BgmChk    = syscom.get_bgm_onoff
			@BgmVol    = syscom.get_bgm_volume
			@VoiceChk  = syscom.get_koe_onoff
			@VoiceTChk = syscom.get_koemode
			@VoiceVol  = syscom.get_koe_volume
			@VFadeChk01= syscom.get_bgmfade_onoff
			@VFadeVol  = syscom.get_bgmfade_volume
			@SeChk     = syscom.get_pcm_onoff
			@SeVol     = syscom.get_pcm_volume
			@SysChk    = syscom.get_se_onoff
			@SysVol    = syscom.get_se_volume
			@MovChk    = syscom.get_mov_onoff
			@MovVol    = syscom.get_mov_volume

// キャラクター別音声 ＯＮ／ＯＦＦ
#macro		@GetCVoiceState(@CV01, @CV02, @CV03, @CV04, @CV05, @CV06, @CV07, @CV08, @CV09, @CV10, @CV11, @CV12, @CV13, @CV14, @CV15, @CV16, @CV17, @CV18, @CV19, @CV20, @CV21, @CV22)
			@CV01 = syscom.get_charakoe_onoff(001)	// 天使
			@CV02 = syscom.get_charakoe_onoff(002)	// ゆり
			@CV03 = syscom.get_charakoe_onoff(003)	// ユイ
			@CV04 = syscom.get_charakoe_onoff(004)	// 岩沢
			@CV05 = syscom.get_charakoe_onoff(005)	// ひさ子
			@CV06 = syscom.get_charakoe_onoff(006)	// 関根
			@CV07 = syscom.get_charakoe_onoff(007)	// 入江
			@CV08 = syscom.get_charakoe_onoff(008)	// 遊佐
			@CV09 = syscom.get_charakoe_onoff(009)	// 椎名
			@CV10 = syscom.get_charakoe_onoff(010)	// 日向
			@CV11 = syscom.get_charakoe_onoff(011)	// 野田
			@CV12 = syscom.get_charakoe_onoff(012)	// 高松
			@CV13 = syscom.get_charakoe_onoff(013)	// 藤巻
			@CV14 = syscom.get_charakoe_onoff(014)	// 大山
			@CV15 = syscom.get_charakoe_onoff(015)	// 松下
			@CV16 = syscom.get_charakoe_onoff(016)	// ＴＫ
			@CV17 = syscom.get_charakoe_onoff(017)	// 竹山
			@CV18 = syscom.get_charakoe_onoff(018)	// チャー
			@CV19 = syscom.get_charakoe_onoff(019)	// 直井
			@CV20 = syscom.get_charakoe_onoff(020)	// 音無
			@CV21 = syscom.get_charakoe_onoff(021)	// その他・男、五十嵐、フィッシュ斉藤
			@CV22 = syscom.get_charakoe_onoff(022)	// その他・女、初音、陽菜子

// キャラクター別音声 ボリューム
#macro		@GetCVoiceVolState(@CVV01, @CVV02, @CVV03, @CVV04, @CVV05, @CVV06, @CVV07, @CVV08, @CVV09, @CVV10, @CVV11, @CVV12, @CVV13, @CVV14, @CVV15, @CVV16, @CVV17, @CVV18, @CVV19, @CVV20, @CVV21, @CVV22)
			@CVV01 = syscom.get_charakoe_volume(001)	// 天使
			@CVV02 = syscom.get_charakoe_volume(002)	// ゆり
			@CVV03 = syscom.get_charakoe_volume(003)	// ユイ
			@CVV04 = syscom.get_charakoe_volume(004)	// 岩沢
			@CVV05 = syscom.get_charakoe_volume(005)	// ひさ子
			@CVV06 = syscom.get_charakoe_volume(006)	// 関根
			@CVV07 = syscom.get_charakoe_volume(007)	// 入江
			@CVV08 = syscom.get_charakoe_volume(008)	// 遊佐
			@CVV09 = syscom.get_charakoe_volume(009)	// 椎名
			@CVV10 = syscom.get_charakoe_volume(010)	// 日向
			@CVV11 = syscom.get_charakoe_volume(011)	// 野田
			@CVV12 = syscom.get_charakoe_volume(012)	// 高松
			@CVV13 = syscom.get_charakoe_volume(013)	// 藤巻
			@CVV14 = syscom.get_charakoe_volume(014)	// 大山
			@CVV15 = syscom.get_charakoe_volume(015)	// 松下
			@CVV16 = syscom.get_charakoe_volume(016)	// ＴＫ
			@CVV17 = syscom.get_charakoe_volume(017)	// 竹山
			@CVV18 = syscom.get_charakoe_volume(018)	// チャー
			@CVV19 = syscom.get_charakoe_volume(019)	// 直井
			@CVV20 = syscom.get_charakoe_volume(020)	// 音無
			@CVV21 = syscom.get_charakoe_volume(021)	// その他・男、五十嵐、フィッシュ斉藤
			@CVV22 = syscom.get_charakoe_volume(022)	// その他・女、初音、陽菜子

// メッセージスピード状態取得
#macro		@GetMSState(@MSChk,@MS)
			@MSChk = syscom.get_message_nowait
			@MS    = syscom.get_message_speed
// メッセージスピード初期状態取得
#macro		@GetMSInitState(@MSChk,@MS)
			syscom.set_message_speed_default
			@MSChk = @OFF
			@MS    = syscom.get_message_speed
// ＭＳＧウィンドウ状態取得
//#macro		@GetWindowBgState(@WB04)
//			@WB04 = syscom.get_filter_color_a

// ＭＳＧウィンドウの初期値取得
//#macro		@GetWindowBgDefaultState(@WB04)
//			syscom.set_filter_color_a_default
//			@WB04 = syscom.get_filter_color_a
// ＭＳＧウィンドウ状態取得
#macro		@GetWindowBgState(@WB01,@WB02,@WB03,@WB04)
			@WB01 = syscom.get_filter_color_r
			@WB02 = syscom.get_filter_color_g
			@WB03 = syscom.get_filter_color_b
			@WB04 = syscom.get_filter_color_a
// ＭＳＧウィンドウの初期値取得
#macro		@GetWindowBgDefaultState(@WB01, @WB02, @WB03, @WB04, @WBChk00)
			syscom.set_filter_color_r_default
			syscom.set_filter_color_g_default
			syscom.set_filter_color_b_default
			syscom.set_filter_color_a_default
			@WB01 = syscom.get_filter_color_r
			@WB02 = syscom.get_filter_color_g
			@WB03 = syscom.get_filter_color_b
			@WB04 = syscom.get_filter_color_a

// ＭＳＧウィンドウのＲセット
#macro		@SetWindowBgRState(@WB01)
			syscom.set_filter_color_r(@WB01)
// ＭＳＧウィンドウのＧセット
#macro		@SetWindowBgGState(@WB02)
			syscom.set_filter_color_g(@WB02)
// ＭＳＧウィンドウのＢセット
#macro		@SetWindowBgBState(@WB03)
			syscom.set_filter_color_b(@WB03)
// ＭＳＧウィンドウのTRセット
#macro		@SetWindowBgTRState(@WB04)
			syscom.set_filter_color_a(@WB04)

// その他
#macro		@GetEtcSetingState(@Es01, @Es02, @Es03, @Es04, @Es05, @Es06, @Es07, @Es08, @Es09, @Es10, @Es11)
			@Es01 = syscom.get_sleep_onoff					// 本プログラムの動作を遅くして、
			@Es02 = syscom.get_no_mwnd_anime_onoff			// メッセージウィンドウの開閉時のアニメを無効にする
			@Es03 = syscom.get_skip_wipe_anime_onoff		// 画面暗転効果をマウスクリックで飛ばす
			@Es04 = syscom.get_wheel_next_message_onoff		// マウスのホイールボタンの下回しで文章を読み進める
			@Es05 = syscom.get_koe_dont_stop_onoff			// 声の再生中に次の文章に進んでも再生を続ける
			@Es06 = @EsAutoSave								// オートセーブを有効化する
			@Es07 = @EsExplainDisp							// 項目の簡易説明を表示する
			@Es08 = @EsSelAutoReset							// 選択肢でオートモードを解除する
			@Es09 = @EsSelSkipReset							// 選択肢でスキップモードを解除する
			@Es10 = @EsBgmDetailDisp						// 再生されるＢＧＭの詳細を表示する
			@Es11 = syscom.get_play_silent_sound_onoff		// サウンド再生時に…
//			@Es06 = syscom.get_skip_unread_message_onoff	// 未読の文章も早送りできるようにする

// オートモード状態取得	待ち時間＝(表示した文字数×文字時間)＋最小時間
#macro		@GetSysAMState(@Check, @TTime, @STime)
			@Check = syscom.get_auto_mode_onoff_flag
			@TTime = syscom.get_auto_mode_moji_wait		// 0～500ﾐﾘ秒
			@STime = syscom.get_auto_mode_min_wait		// 0～10000ﾐﾘ秒 ※設定値は100ﾐﾘ秒単位なので端数切捨て

// オートモード初期状態取得	待ち時間＝(表示した文字数×文字時間)＋最小時間
#macro		@GetSysAMDefState(@Check, @TTime, @STime)
			syscom.set_auto_mode_moji_wait_default
			syscom.set_auto_mode_min_wait_default
			@Check = @OFF
			@TTime = syscom.get_auto_mode_moji_wait		// 0～500ﾐﾘ秒
			@STime = syscom.get_auto_mode_min_wait		// 0～10000ﾐﾘ秒 ※設定値は100ﾐﾘ秒単位なので端数切捨て

// 各桁の数値を個別抽出３桁 文字時間
#macro		@NUM_ABSTRACT01(@BASE, @NUM01, @NUM02, @NUM03)
			@NUM01 =  @BASE / 100
			@NUM02 = (@BASE - ( @NUM01 * 100)) / 10
			@NUM03 =  @BASE - ((@NUM01 * 100) + (@NUM02 * 10))

// 各桁の数値を個別抽出４桁 最小時間
#macro		@NUM_ABSTRACT02(@BASE, @NUM01, @NUM02, @NUM03, @NUM04)
			@NUM01 =  @BASE / 1000
			@NUM02 = (@BASE - ( @NUM01 * 1000)) / 100
			@NUM03 = (@BASE - ((@NUM01 * 1000) + (@NUM02 * 100))) / 10
			@NUM04 = (@BASE - ((@NUM01 * 1000) + (@NUM02 * 100) + (@NUM03 * 10)))

// 各桁の数値を個別抽出５桁 待ち時間
#macro		@NUM_ABSTRACT03(@BASE, @NUM01, @NUM02, @NUM03, @NUM04, @NUM05)
			@NUM01 =  @BASE / 10000
			@NUM02 = (@BASE - ( @NUM01 * 10000)) / 1000
			@NUM03 = (@BASE - ((@NUM01 * 10000) + (@NUM02 * 1000))) / 100
			@NUM04 = (@BASE - ((@NUM01 * 10000) + (@NUM02 * 1000) +(@NUM03 * 100))) / 10
			@NUM05 = (@BASE - ((@NUM01 * 10000) + (@NUM02 * 1000) +(@NUM03 * 100) + (@NUM04 * 10)))


